version: "3.7"
services:
  mysql:
    image: mysql:5.7.37
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=person
      - MYSQL_PASSWORD=wesleyosantos91
      - MYSQL_DATABASE=person